
name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker Image
        run: docker build -t parzival2808/frontend-react:latest --build-arg REACT_APP_SERVER_BASE_URL=${{secrets.REACT_APP_SERVER_BASE_URL}} .
      

      - name: Delete old container  
        run: docker rm -f frontend-react-app-container || true

      - name: Publish Image to Docker Hub
        run: docker push parzival2808/frontend-react:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull parzival2808/frontend-react:latest

      - name: Stop and remove existing container (if running)
        run: docker rm -f frontend-react-app-container || true
      
      
      - name: Run Docker Container
        run: docker run -d -p 443:80 --name frontend-react-app-container parzival2808/frontend-react:latest
